In [1]:
import numpy as np 

# Aray de 1 Dimension 

In [2]:
numeros=np.array([1,2,3,4,5,6], np.int16)
type(numeros)
print(numeros)
#Aceder en 1-D a travez de un unico elemento 
print(numeros[-1])

[1 2 3 4 5 6]
6


In [3]:
niter = 4
ndims = 10 ** np.arange(2, 2 + niter)

print(ndims)


[   100   1000  10000 100000]


In [4]:
n=5
x = np.array([0.25] * n)

print(x)

[0.25 0.25 0.25 0.25 0.25]


# Array Bidimensional 

In [5]:
M= np.array([[1,2,3],[4,5,5]])
print(M)
print(M[0,2])

[[1 2 3]
 [4 5 5]]
3


# Array tridimensiona

# informacion de una matriz

In [6]:
M= np.array([[1,2,3],[4,5,5]])
print(f"El numero de filas es : {M.shape[0]} y el numero de columnas es {M.shape[1]}")

El numero de filas es : 2 y el numero de columnas es 3


In [7]:
import numpy as np
from numpy.linalg import matrix_rank

# Create an array
arr = np.eye(5)

# Display the array
print("Our Array...\n",arr)

# Check the Dimensions
print("\nDimensions of our Array...\n",arr.ndim)

# Get the Datatype
print("\nDatatype of our Array object...\n",arr.dtype)

# Get the Shape
print("\nShape of our Array object...\n",arr.shape)

# To Return matrix rank of array using Singular Value Decomposition method, use the numpy.linalg.matrix_rank() method in Python
print("\nResult (rank)...\n",matrix_rank(arr))

Our Array...
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Dimensions of our Array...
 2

Datatype of our Array object...
 float64

Shape of our Array object...
 (5, 5)

Result (rank)...
 5


# Dicas con biblioteca Numpy

# Funcion np.random

- `np.random.rand()`: Genera números aleatorios distribuidos uniformemente en el intervalo [0, 1].
- `np.random.randn()`: Genera números aleatorios distribuidos normalmente con media 0 y desviación estándar 1.
- `np.random.randint()`: Genera números enteros aleatorios dentro de un rango especificado.
- `np.random.shuffle()`: Mezcla aleatoriamente los elementos de una secuencia.
- `np.random.choice()`: Genera una muestra aleatoria de una secuencia dada.
- `np.random.permutation()`: Devuelve una permutación aleatoria de una secuencia dada.


In [8]:
M= np.array([[1,2,3],[4,5,6],[7,8,9]])
#M=np.linspace(0,1,10)

# función de NumPy que genera una permutación aleatoria de un conjunto de números, toma como variable un entero 
random_matrix = np.random.permutation(
    M.shape[0] * M.shape[1]
)
# imprime un array con la totalidad de los elementos de una matriz 
print(random_matrix)

[5 3 8 6 2 0 1 4 7]


In [9]:
# Primer ejemplo 
l=np.random.rand(2,2)
print(l)

[[0.92061578 0.19908046]
 [0.16889774 0.68036851]]


# Funcion .reshape()


La función `reshape ()` en NumPy se utiliza para cambiar la forma (dimensiones) de un array sin cambiar sus datos subyacentes. Básicamente, toma un array existente y lo remodela en una nueva forma especificada por el usuario.

In [10]:
# Crear un array unidimensional con 12 elementos
arr = np.arange(12)
# Utilizar reshape para convertirlo en una matriz de 3 filas y 4 columnas
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
# Genera el mismo codigo pero como una matriz 
# Random matrix corresponde a un array con lo slementos de la matriz original 
# Reshape se utiliza para cambiar un array a una forma especial 

random_matrix = random_matrix.reshape(
    M.shape[1], M.shape[0]
)

print(random_matrix)


[[5 3 8]
 [6 2 0]
 [1 4 7]]


# Funcion np.linalg.norm()-Norma de una matriz

In [12]:
m=np.array([[1,2],[3,4]])
print(f"la norma del la matriz es {np.linalg.norm(m):.2f}")

la norma del la matriz es 5.48


# Funcion np.arange()-crear array con num esp
la funcion es de la forma `numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)`

In [13]:
a=np.arange(0, 5, 0.5, dtype=int)
a=np.arange(-3, 3, 0.5, dtype=int)
print(a)

[-3 -2 -1  0  1  2  3  4  5  6  7  8]


In [14]:
power = 40
modulo = 10000

# range(8) genera una secuencia de enteros
# np.arange(8) genera una secuencia de números de punto flotante. Esto significa que los valores en x1 serán enteros, mientras que los valores en x2 serán números de punto flotante.

x1 = [(n ** power) % modulo for n in range(8)]
x2 = [(n ** power) % modulo for n in np.arange(8)]

print(x1)

print(x2)

[0, 1, 7776, 8801, 6176, 625, 6576, 4001]
[0, 1, 7776, 7185, 0, 5969, 4816, 3361]


In [15]:
niter = 4
ndims = 10**np.arange(2, 2 + niter)

print(ndims)

[   100   1000  10000 100000]


In [16]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


## Funcion np.round()

In [17]:
import numpy as np

# Crear un array con valores decimales
arr = np.array([1.234, 2.454, 3.786, 4.991])

# Redondear los elementos del array a dos decimales
rounded_arr = np.round(arr, decimals=2)

print(rounded_arr)


[1.23 2.45 3.79 4.99]


# Funcion np.log()

In [18]:
import numpy as np

# Crear un array con algunos valores
arr = np.array([1, 2, 3, 4, 5])

# Calcular el logaritmo natural de cada elemento del array
log_arr = np.log(arr)

print(log_arr)


[0.         0.69314718 1.09861229 1.38629436 1.60943791]


# Fucnion np.round ()

Redondear los elementos de un array a la cantidad de decimales especificada. Su sintaxis básica es la siguiente:

numpy.round(a, decimals=0, out=None)


# Construccion de matrices con Arrays 

In [19]:
import numpy as np

# Crear algunos arrays de ejemplo
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array([7, 8, 9])

# Apilar verticalmente
matriz_vertical = np.vstack([array1, array2, array3])

print(matriz_vertical)
print(matriz_vertical.shape)

# Apilar horizontalmente
matriz_horizontal = np.hstack([array1[:, np.newaxis], array2[:, np.newaxis], array3[:, np.newaxis]])

print(matriz_horizontal)
print(matriz_horizontal.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[1 4 7]
 [2 5 8]
 [3 6 9]]
(3, 3)


# Extraer una fila desde una matriz 

In [20]:
import numpy as np

# Crear una matriz de ejemplo
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extraer la primera fila
primera_fila = matriz[0, :]  # Seleccionar la primera fila y todas las columnas

print("Primera fila:", primera_fila)  # [1, 2, 3]


Primera fila: [1 2 3]


#  Extraer una columna desde una matriz 

In [21]:
# Extraer la primera columna
primera_columna = matriz[:, 0]  # Seleccionar todas las filas y la primera columna

print("Primera columna:", primera_columna)  # [1, 4, 7]


Primera columna: [1 4 7]
