# Utilizando Numpy

In [94]:
# Imports
 
import matplotlib.pyplot as plt
import numpy as np
from scipy.linalg import svd
 
"""
Singular Value Decomposition (SVD) 
"""
import numpy as np
 
#Creating a matrix A
A = np.array([[3,3,2],[2,3,-2],[2,4,-2]])
 
#Performing SVD
U, D, VT = np.linalg.svd(A)


#Checking if we can remake the original matrix using U,D,VT
A_remake = (U @ np.diag(D) @ VT)

print(A_remake)


[[ 3.  3.  2.]
 [ 2.  3. -2.]
 [ 2.  4. -2.]]


In [95]:
import numpy as np
import numpy.linalg as LA
import matplotlib.pyplot as plt

In [97]:
np.set_printoptions(precision=2)

# Define the matrix
A=matriz_aleatoria = np.random.normal(loc=5, scale=15, size=(5, 5))


# Compute the SVD of the matrix
U, S, V = np.linalg.svd(A,full_matrices=True)

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(A)

# Print the rank of the matrix
print("Rank of matrix:\n", rank)
print("\n")

print("S: \n", S)
print("\n")
#Checking if we can remake the original matrix using U,D,VT

A_remake = (U @ np.diag(S) @ V.T)

print("la matriz original es:")
print(A)
print("\n")
print("la matriz Reconstruida es:")
print(A_remake)
print("\n")
print(A-A_remake)
print("\n")
print(np.linalg.norm(A)-np.linalg.norm(A_remake))

Rank of matrix:
 5


S: 
 [60.14 42.45 20.13  7.62  2.98]


la matriz original es:
[[ -4.48  17.27  28.03  -6.04  21.42]
 [  7.87   5.37  -9.51   9.81 -11.35]
 [-27.55 -12.68  18.44 -26.83  21.81]
 [ -8.52   3.25   2.46  13.88   8.42]
 [ -3.35  15.61  10.9   26.41  -2.36]]


la matriz Reconstruida es:
[[-21.62   8.39 -27.97  13.17  10.28]
 [ 10.15   1.16  13.41  -2.8   10.7 ]
 [-14.74  -4.52 -34.3    9.66 -30.8 ]
 [  0.74  17.15  -6.27  -4.21   1.16]
 [  6.85  19.33  -8.74  -8.4   22.57]]


[[ 17.13   8.88  56.   -19.21  11.14]
 [ -2.27   4.2  -22.93  12.62 -22.05]
 [-12.82  -8.16  52.73 -36.49  52.61]
 [ -9.27 -13.9    8.74  18.09   7.26]
 [-10.2   -3.72  19.65  34.81 -24.93]]


2.842170943040401e-14
