# Operaciones con listas en Np.meshgrid()

In [5]:
import numpy as np

x= np.linspace(1,3,3)

y= x= np.linspace(3,5,3)

x_1, y_1 = np.meshgrid(x, y)
 
print("x_1 = ")
print(x_1)
print("y_1 = ")
print(y_1)

x_1 = 
[[3. 4. 5.]
 [3. 4. 5.]
 [3. 4. 5.]]
y_1 = 
[[3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]]


In [3]:
import numpy as np

x= np.linspace(1,3,3)

y= np.array([[5, 6],
                   [7, 8]])

x_1, y_1 = np.meshgrid(x, y)
 
print("x_1 = ")
print(x_1)
print("y_1 = ")
print(y_1)

x_1 = 
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
y_1 = 
[[5 5 5]
 [6 6 6]
 [7 7 7]
 [8 8 8]]


# Operaciones con Matrices  en Np.meshgrid()

In [4]:
import numpy as np

x = np.array([[1, 2],
              [3, 4],[3, 4]])

y = np.array([[1, 2],
              [3, 4]])

# Aplanar las matrices
x_flat = x.flatten()
y_flat = y.flatten()

# Crear la cuadrícula
x_1, y_1 = np.meshgrid(x_flat, y_flat)

print("x_1 = ")
print(x_1)
print("y_1 = ")
print(y_1)


x_1 = 
[[1 2 3 4 3 4]
 [1 2 3 4 3 4]
 [1 2 3 4 3 4]
 [1 2 3 4 3 4]]
y_1 = 
[[1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [3 3 3 3 3 3]
 [4 4 4 4 4 4]]
